#!/usr/bin/env bash
source /root/source.txt

set -o errexit
set -o pipefail
set -o nounset

echo 'nameserver 8.8.8.8' > /etc/resolv.conf
echo 'nameserver 8.8.4.4' >> /etc/resolv.conf

mount -t proc proc proc/
mount -t sysfs sys sys/

export DEBIAN_FRONTEND="noninteractive"

apt-get update
apt-get install -y apt-utils
apt install -y locales locales-all
echo
echo Installing rpi-img-builder base.
sleep 1s
apt -y clean
apt -y autoclean
apt update
apt upgrade -y
apt install -y ${PKGS1} ${DEV2} ${FIRMWARE}
apt -y clean
apt -y autoclean

umount /proc /sys
