#!/bin/bash
#AARCH64 ROOTFS
source lib/source.txt

wget -cq --show-progress https://github.com/pyavitz/rootfs-tarballs/releases/download/rootfs/devuan-${DEVUAN_VERSION}-rootfs-aarch64.tar.xz

set -x
RAM=0
PROXY=""
IMAGE_FOLDER="img/"

set -eux -o pipefail
IMAGE_LINUX_LOADADDR="0x1080000"
IMAGE_FILE_SUFFIX="$(date +%F)"
IMAGE_FILE_NAME="devuan-${DEVUAN_VERSION}-rootfs-aarch64.img"
if [ $RAM -ne 0 ]; then
	IMAGE_FOLDER="ram/"
fi
mkdir -p "$IMAGE_FOLDER"
if [ $RAM -ne 0 ]; then
	mount -t tmpfs -o size=3G tmpfs $IMAGE_FOLDER
fi
truncate -s 1850MB "${IMAGE_FOLDER}${IMAGE_FILE_NAME}"
fdisk "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" <<EOF
o
n
p
1
2048
a
t
b
3613280

p
w

EOF
IMAGE_LOOP_DEV="$(losetup --show -f ${IMAGE_FOLDER}${IMAGE_FILE_NAME})"
IMAGE_LOOP_DEV_ROOTFS="${IMAGE_LOOP_DEV}p1"
partprobe "${IMAGE_LOOP_DEV}"
mkfs.ext4 -L ROOTFS "${IMAGE_LOOP_DEV_ROOTFS}"
mkdir -p p1
mount "${IMAGE_LOOP_DEV_ROOTFS}" p1
sync
umount p1
mount -o defaults,noatime "${IMAGE_LOOP_DEV_ROOTFS}" p1

### Rootfs
tar -xf devuan-${DEVUAN_VERSION}-rootfs-aarch64.tar.xz -C p1/

mkdir -p p1/etc/apt/apt.conf.d p1/etc/dpkg/dpkg.cfg.d
echo "force-unsafe-io" > "p1/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io"

mkdir -p p1/usr/bin
cp $(which "qemu-aarch64-static") p1/usr/bin

tee p1/etc/apt/sources.list <<EOF
deb http://deb.devuan.org/merged ${DEVUAN_VERSION} main contrib non-free
deb http://deb.devuan.org/merged ${DEVUAN_VERSION}-updates main contrib non-free
deb http://deb.devuan.org/merged ${DEVUAN_VERSION}-security main contrib non-free
deb http://deb.devuan.org/merged ${DEVUAN_VERSION}-backports main contrib non-free
EOF

if [ -n "$PROXY" ] ; then
	tee "p1/etc/apt/apt.conf.d/30proxy" <<EOF
Acquire::http::proxy "http://127.0.0.1:3142";
EOF
fi


# setup devuan-stage2
cp scripts/devuan-stage2 p1/root
cp lib/source.txt p1/root

# mount and chroot
mount -o bind /dev p1/dev
mount -o bind /dev/pts p1/dev/pts
chroot p1 /root/devuan-stage2

# unmount
umount p1/dev/pts
umount p1/dev

# clean
rm p1/usr/bin/qemu-aarch64-static
rm p1/root/devuan-stage2
rm p1/root/source.txt
rm p1/etc/apt/sources.list
rm -f p1/var/cache/debconf/*

if [ -n "$PROXY" ] ; then
	rm p1/etc/apt/apt.conf.d/30proxy
fi
rm p1/etc/dpkg/dpkg.cfg.d/dpkg-unsafe-io

### Finish
e4defrag -c p1

cd p1
tar cfJ ../devuan-${DEVUAN_VERSION}-rootfs-aarch64.tar.xz *
cd ..

umount p1

losetup -d "${IMAGE_LOOP_DEV}"
mv "${IMAGE_FOLDER}${IMAGE_FILE_NAME}" "${IMAGE_FILE_NAME}"
if [ $RAM -ne 0 ]; then
	umount "${IMAGE_FOLDER}"
fi
rmdir "${IMAGE_FOLDER}"
rmdir p1
rm -f devuan-${DEVUAN_VERSION}-rootfs-aarch64.img
